package com.coded.bankingproject.enums

enum class ErrorCode {
    ACCOUNT_NOT_FOUND,
    ACCOUNT_LIMIT_REACHED,ACCOUNT_EXCEPTION,
    ACCOUNT_ERROR,
    INVALID_ACCOUNT_TYPE,
    INVALID_AMOUNT,
    INVALID_FUNDS,
    INVALID_CURRENCY,
    INVALID_TRANSFER,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    USER_ID_NOT_FOUND,
    INVALID_AGE,
    INVALID_SALARY,
}