package com.coded.bankingproject.errors

enum class ErrorCode {
    ACCOUNT_NOT_FOUND,
    ACCOUNT_LIMIT_REACHED,
    ACCOUNT_USER_ALREADY_EXISTS,
    ACCOUNT_VERIFICATION_EXCEPTION,
    INVALID_ACCOUNT_TYPE,
    INVALID_AMOUNT,
    INVALID_FUNDS,
    INVALID_TRANSFER,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    USER_ID_NOT_FOUND,
    INVALID_AGE,
    INTERNAL_SERVER_ERROR,
}